services:
  zili-api:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: zili
    depends_on:
      - postgresql
    restart: always
    networks:
      - zili-net

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zili
    ports:
      - "5432:5432"
    volumes:
      - ~/project/db/data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    networks:
      - zili-net

  postgresql-restore:
    image: postgres
    environment:
      PGPASSWORD: password
    volumes:
      - ~/backups/postgresql:/backups
    networks:
      - zili-net
    depends_on:
      - postgresql
    profiles:
      - restore
    command: >
      psql -h postgresql -U user -d zili -f /backups/zili_full_latest.sql

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472:472"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - postgresql
    restart: always
    networks:
      - zili-net

networks:
  zili-net:
    driver: bridge

